slam_toolbox:
  ros__parameters:
    odom_frame: "odom"
    base_frame: "base_link"
    map_frame: "map"
    scan_topic: "/scan"
    odom_topic: "/odom"
    use_sim_time: false
    mode: "online_sync"
    max_laser_range: 12.0
    minimum_time_interval: 0.05
    update_interval: 0.05

controller_server:
  ros__parameters:
    use_sim_time: false
    controller_plugins: ["FollowPath"]
    odom_topic: "/odom"

    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"

planner_server:
  ros__parameters:
    use_sim_time: false
    planner_plugins: ["GridBased"]
    odom_topic: "/odom"

    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"

local_costmap:
  local_costmap:
    ros__parameters:
      global_frame: "odom"
      robot_base_frame: "base_link"
      update_frequency: 5.0
      publish_frequency: 1.0
      use_sim_time: false
      resolution: 0.05
      footprint: "[[0.2, 0.2], [0.2, -0.2], [-0.2, -0.2], [-0.2, 0.2]]"
      plugins: ["obstacle_layer", "inflation_layer"]

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"

